### ISSUE TITLE
Change love from local to global

### ISSUE THREAD

**Issue by Michcioperz** [MikuAuahDark/love2d-tl#2]
Hi, first of all, thanks for creating this.
I am new to Teal but I have a bit of experience with Love2D from long ago and I was thinking if it wouldn't be better to change `local love` to `global love`.
I tried to use your typings and right now to make it work I'd have to either `local love = require('love')` or `global love = require('love')` in my code. This makes tl place `love = require('love')` in the resulting Lua files. I tried running that right now and it works, but I was thinking that maybe it would be better to just make `love` a `global` in love.d.tl and then preload it for type checking using [tl options](https://github.com/teal-language/tl/blob/master/docs/compiler_options.md#compiler-options).
Please do let me know if what happens currently is actually a good situation, I've been out of the loop for a good while, I've yet to properly catch up with API changes since Love2D 0.9, so I presume best practices might have changed as well.

**Comment by MikuAuahDark** [comment]
I think that's good idea. I normally use `local love = require("love")` idiom for all my LOVE projects but accessing global `love` is fine as of 11.3.

**Comment by MikuAuahDark** [comment]
Note that because Teal lack of class inheritance system, you have to cast in many cases.
```lua
local love = require("love")

local mesh: love.graphics.Mesh -- Remember the type of this variable is love.graphics.Mesh

function love.load(arg: {string}, _: {string})
	mesh = love.graphics.newMesh({
		{100, 100, 0, 0, 1, 0, 0, 1},
		{200, 100, 0, 0, 0, 1, 0, 1},
		{100, 200, 0, 0, 0, 0, 1, 1},
	}, "triangles", "static")
end

function love.draw()
	love.graphics.draw(mesh as love.graphics.Drawable) -- Notice that we have to cast it to love.graphics.Drawable or Teal checker will spit errors.
end
```
Don't worry, casting is there for convenience. The generated Lua code is as follows
```lua
local love = require("love")

local mesh

function love.load(arg, _)
   mesh = love.graphics.newMesh({
      { 100, 100, 0, 0, 1, 0, 0, 1 },
      { 200, 100, 0, 0, 0, 1, 0, 1 },
      { 100, 200, 0, 0, 0, 0, 1, 1 },
   }, "triangles", "static")
end

function love.draw()
   love.graphics.draw(mesh)
end
```
LOVE-specific notes: Color ranges are now 0...1 since 11.0, so if your game only outputs black or white, you may want to check your color range.
