### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Aidymouse** [MikuAuahDark/love2d-tl#5]
Hi there, this looks rad! Looks like exactly what I want, except I'm a bit of a noob and I don't know how to go from this repo to being able to use type annotations in my love2d code! Any tips?

**Comment by MikuAuahDark** [comment]
Hello, unfortunately this has not been updated to latest Teal definition syntax.

**Comment by Aidymouse** [comment]
Hey there,
That's all right, I was a total teal noob up to this point, managed to struggle to get it all working on my Linux machine finally only the find everything breaking when I tried to import type declaration files of any kind! 

What a headache! I think I'm just gonna stick with the [fancy language server](https://github.com/sumneko/lua-language-server) , that's good enough for me.

**Comment by MikuAuahDark** [comment]
Yeah, sorry for the inconveniece. Looks like I need to find someone to maintain this.

**Comment by jmhimara** [comment]
Is this still out of date or can it be used? Looks like it should be compatible with Love 11.4.
